name: Blynk Toggle Twice Daily

on:
  schedule:
    - cron: '00 15 * * *'  # Runs at 14:40 UTC = 10:40 PM UTC+8
  workflow_dispatch: # allows manual trigger from GitHub

jobs:
  toggle-blynk:
    runs-on: ubuntu-latest

    steps:
      - name: Turn ON Blynk Pin
        run: |
          curl "https://blynk.cloud/external/api/update?token=${{ secrets.BLYNK_TOKEN }}&V1=0"
          sleep 240  # 4 minutes
          curl "https://blynk.cloud/external/api/update?token=${{ secrets.BLYNK_TOKEN }}&V1=1"
