name: Blynk Toggle

on:
  schedule:
    - cron: '30 15 * * *'  # 11:05 PM Malaysia time (UTC+8)
  workflow_dispatch:      # allows manual trigger

jobs:
  trigger-blynk:
    runs-on: ubuntu-latest
    steps:
      - name: Call Blynk API to set V1 to 0
        run: |
          curl -L -s -o response.txt -w "%{http_code}" "https://blynk.cloud/external/api/update?token=vkNgFrghz7U5lXtxmtxPXg0PMtUKAPFp&V1=0"
          echo "Response:"
          cat response.txt
