name: Blynk Toggle

on:
  schedule:    
    - cron: '52 22,10 * * *'  # 6:52 AM and 6:52 PM Malaysia Time (UTC+8)
  workflow_dispatch:          # allows manual trigger

jobs:
  trigger-blynk:
    runs-on: ubuntu-latest
    steps:
      - name: Call Blynk API to set V1 to 0 (with retry)
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Setting V1 to 0"
            STATUS=$(curl -L -s -o response.txt -w "%{http_code}" "https://blynk.cloud/external/api/update?token=vkNgFrghz7U5lXtxmtxPXg0PMtUKAPFp&V1=0")
            echo "Response code: $STATUS"
            cat response.txt
            if [ "$STATUS" -eq 200 ]; then
              break
            fi
            sleep 10
          done

      - name: Wait for 4 minutes
        run: sleep 240

      - name: Call Blynk API to set V1 to 1 (with retry)
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Setting V1 to 1"
            STATUS=$(curl -L -s -o response.txt -w "%{http_code}" "https://blynk.cloud/external/api/update?token=vkNgFrghz7U5lXtxmtxPXg0PMtUKAPFp&V1=1")
            echo "Response code: $STATUS"
            cat response.txt
            if [ "$STATUS" -eq 200 ]; then
              break
            fi
            sleep 10
          done
